Document: staticmirror
Title: Debian staticmirror Manual
Author: <insert document author here>
Abstract: This manual describes what staticmirror is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/staticmirror/staticmirror.sgml.gz

Format: postscript
Files: /usr/share/doc/staticmirror/staticmirror.ps.gz

Format: text
Files: /usr/share/doc/staticmirror/staticmirror.text.gz

Format: HTML
Index: /usr/share/doc/staticmirror/html/index.html
Files: /usr/share/doc/staticmirror/html/*.html
